title: "microCMSマニュアル"
summary: "非エンジニアにもおすすめ出来るmicroCMSのマニュアルです。非公式です。
私は教育現場というITリテラシーが低いとされる現場で仕事をしています。
そんな経験をしているからこそ出来るmicroCMSの使用方法を紹介します。"
topics: ["microcms", "jamstack"]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - introduction
  - introduction2
  -
